# Generated by Django 3.2.15 on 2022-08-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_last_name_user_option'),
        ('TODO_app', '0002_auto_20220810_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=256)),
                ('actual', models.BooleanField(blank=True, null=True)),
                ('project', models.ManyToManyField(to='TODO_app.Project')),
                ('users', models.ManyToManyField(to='user_app.User')),
            ],
        ),
    ]
