# Generated by Django 3.2.15 on 2022-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_app', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
