# Generated by Django 3.2.15 on 2022-08-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_first_name_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='option',
        ),
    ]
